#!/usr/bin/env sh
set -eo pipefail
[[ "$TRACE" ]] && set -x

out() {
  echo "** $@"
}

run_escape_to() {
  exec "$@"
}

run() {
  cd ${MOUNTPOINT}
  cp -rp /tmp/${PYPY_VERSION} .
  ln -f -n -s ./${PYPY_VERSION} pypy
}

main() {
  case "$1" in
  escto)
    shift; run_escape_to "$@";;
  *)
    run "$@";;
  esac
}

main "$@"
